language: ruby
rvm:
    - 2.2
    - 2.1
    - 2.0
# http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci
cache: bundler
sudo: false
git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - gem update --system
    - gem --version

# Assume bundler is being used, install step will run `bundle install`.
script: ./scripts/cibuild.sh

branches:
    only:
        - deploy_branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
    email:
        on_failure: always
