#
# This file contains configuration flags to customize the site
#

# Site settings
# Name of your site (displayed in the header)
name: Jekyllifed-Gregreda
title: Gregreda mets Ruby
about_header: "Nice to meet you"

# Short bio or description (displayed in the header)
description: # this means to ignore newlines until "baseurl:"
  #My thoughts and experiences working in the software field. I'll going over various tools
  #I've used within my development projects as well as those I usee to maintain this blog. I may even post strategies on being productive at work.
timezone: America\New_York

# Creator settings
creator: "One and All"
# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://raw.githubusercontent.com/user/user.github.io/master/images/logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: example@mail.net
#  flickr:
  github_username: jekyll
#  instagram:
  linkedin_url: https://www.linkedin.com/pub/path
#  pinterest:
#  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
#  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus: identifier

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics:

# Build Settings
## Conversion
markdown: kramdown
highlighter: coderay #or rouge
#lsi: true // Boolean to determine to produce an index for related posts.
## Where things are
source: content
destination: output
## Handling Reading
safe: false
encoding: "utf-8"
# Exclude these files from your production _site
exclude:
  - [vendor]
  - content/vacuum/LICENSE
  - content/vacuum/README.md
#include:
#keep_files:
## Filtering Content
limit_posts: 5
future: false
unpublished: false
permalink: /:title/
# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # Minified using :compressed, other choice is :expanded

# Build Plugins
whitelist: []
gems:
   - jekyll-mentions
   - jekyll-redirect-from
   - jemoji
   - jekyll-sitemap
   - jekyll-feed

AVATAR: '/theme/images/avatar.jpg'
# TODO: switch to /blog/slug/index.html -- need to setup redirects first
ARTICLE_URL: '{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS: '{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'
# Static Pages
PAGE_PATHS: ['pages']
PAGE_URL: '{slug}/'
PAGE_SAVE_AS: '{slug}/index.html'
ABOUT_PAGE_HEADER: 'Nice to meet you.'
CODE_DIR: 'code'
NOTEBOOK_DIR: 'notebooks'

TWITTER_CARDS: True
TWITTER_NAME: "gjreda"
GITHUB_NAME: 'gjreda'
LINKEDIN_URL: 'http://linkedin.com/in/gjreda'
GOOGLE_PLUS_URL: 'https://plus.google.com/111658599948853828157?rel=author'
LASTFM_NAME: 'gjreda'

#### Analytics
GOOGLE_ANALYTICS: 'UA-34295039-1'
DOMAIN: "gregreda.com"

# Other
MAILCHIMP: True
CACHE_CONTENT: False
AUTORELOAD_IGNORE_CACHE: True

# Serve settings
detach: false
host: localhost
port: 716
# Your website URL (e.g. http://stargator.github.io)
# Used for Sitemap.xml and your RSS feed
url: "http://localhost:716" # the base hostname & protocol for your site
# If hosting site at a Project repository on GitHub pages
# (http://username.github.io/repository-name)
# and NOT the User repository (http://username.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "" # the subpath of the site, e.g. /blog/

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: {{ site.creator}}

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

excerpt_separator: ""
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true
  input: GFM

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# Define custome collections (ie: drafts, pages, posts
#collections:

# Feed Settings
#feed_all_atom: /feed/feed.xml
feed:
  path: /feed/feed.xml
